version: '3.9'
services:
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - db
  db:
    image: mariadb:10.7
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    env_file: .env.local
    environment:
      - MARIADB_DATABASE=production
      - TZ=Europe/Berlin
  proxy:
    image: nginx:1.21-alpine
    container_name: proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    environment:
      - TZ=Europe/Berlin
