version: '3.9'
services:
  web:
    build: .
    restart: always
    ports:
      - '80:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
  db:
    image: mariadb:10.7
    restart: always
    env_file: .env.local
    environment:
      - MARIADB_DATABASE=production
